# 

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
oneDDArray = np.array([1,2,3,4,5])
print(oneDDArray)

[1 2 3 4 5]


In [ ]:
Sprawdzanie wymiary tablicy

In [8]:
print(ondeDArray.ndim)


1


In [34]:
twoDArray = np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(twoDArray)

[[1 2 3 4 5]
 [5 4 3 2 1]]


In [11]:
print(twoDArray.ndim)

2


In [12]:
threeDArray = np.array([[[1,2,3],[-1,-2,-3]],[[4,5,6],[-4,-5,-6]]])
print(threeDArray)

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]


In [13]:
print(threeDArray.ndim)

3


In [20]:
print(twoDArray)
print(twoDArray[1][0])
print(twoDArray[1])


[[1 2 3 4 5]
 [5 4 3 2 1]]
5
[5 4 3 2 1]


In [30]:
print(threeDArray)

print(threeDArray[1][0][1])
print(threeDArray[1][1][0])
print(threeDArray[0][1][2])

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]
5
-4
-3


In [32]:
print(threeDArray)
print(threeDArray.shape)


[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]
(2, 2, 3)


In [36]:
for i in twoDArray:
    print(i)

[1 2 3 4 5]
[5 4 3 2 1]


In [39]:
for i in twoDArray:
    for j in i:
        print(j)

1
2
3
4
5
5
4
3
2
1


In [40]:
for i in threeDArray:
    for j in i:
        for k in j:
            print(k)

1
2
3
-1
-2
-3
4
5
6
-4
-5
-6


In [42]:
zerosArray = np.zeros(10)
print(zerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [43]:
onesArray= np.ones(10)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [48]:
onesArray = onesArray.astype(int)

In [49]:
print(onesArray)

[1 1 1 1 1 1 1 1 1 1]


In [51]:
fivesArray = np.full(10,5.4)
print(fivesArray)

[5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4]


In [52]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [53]:
print(matrix + 2)

[[3 4 5]
 [6 7 8]]


In [ ]:
w listach tak nie mozna 

In [55]:
print(matrix*2)

[[ 2  4  6]
 [ 8 10 12]]


In [56]:
pythonList = [[1,2,3],[4,5,6]]
print(pythonList*2)

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


In [57]:
print(matrix/2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [58]:
print(matrix//2)

[[0 1 1]
 [2 2 3]]


In [59]:
print(matrix**2)

[[ 1  4  9]
 [16 25 36]]


In [60]:
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [62]:
matrix2=np.array([[-1,-2,-3],[-4,-5,-6]])
print(matrix2)


[[-1 -2 -3]
 [-4 -5 -6]]


In [64]:
print(matrix+matrix2)

[[0 0 0]
 [0 0 0]]


In [65]:
print(matrix*matrix2)

[[ -1  -4  -9]
 [-16 -25 -36]]


In [66]:
print(matrix/matrix2)

[[-1. -1. -1.]
 [-1. -1. -1.]]


In [68]:
print(matrix//matrix2)

[[-1 -1 -1]
 [-1 -1 -1]]


In [70]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [71]:
print(matrix2)

[[-1 -2 -3]
 [-4 -5 -6]]


In [74]:
m1=np.array([[1,2,3],[4,5,6],[0,0,0]])
m2=np.array([[-1,-2,-3,],[-4,-5,-6],[0,0,0]])


In [75]:
np.matmul(m1,m2)

array([[ -9, -12, -15],
       [-24, -33, -42],
       [  0,   0,   0]])

In [76]:
np.min(m1)

0

In [77]:
np.max(m1)

6

In [78]:
np.sum(m1)

21

In [80]:
np.mean(m1)


2.3333333333333335

In [81]:
np.std(m1)

2.160246899469287

In [82]:
np.median(m1)

2.0